### ISSUE TITLE
Scrolling Dotted Line is invisible after importing URP

### ISSUE THREAD

**Issue by BRousserie** [silverua/slay-the-spire-map-in-unity#13]
Hello,
Thank you for your work !
I just had an issue after importing [this](https://assetstore.unity.com/packages/vfx/shaders/2d-glowy-dissolve-shader-graph-164638) Asset Store Package which relies on Universal Render Pipeline and Shader Graph : the Scrolling Dotted Lines were not visible anymore.

I'm not used to unity shaders, URP or Shader Graph at all at the moment so I don't know if it's easiely solvable or not. I hope you have a better clue about this issue !

**Comment by silverua** [comment]
Hi. Thanks for reaching out!
My understanding is that - importing that package also switched your project over to Universal Render Pipeline (URP). URP uses its own set of shaders and old shaders for the default "Built-in render pipeline" do not work with URP. 
One of these old shaders was used for the scrollable dotted line on the map. 
The options are: 
1. Switch back to built-in render pipeline, take full advantage of the scrollable line shader provided in this repo.
2. Find or create a similar shader that scrolls a texture and works with URP. 
I am not a shader / Shader Graph specialist myself, so I can't help with point 2, unfortunately. But that's the direction I'd look into if I wanted to stay on URP.

**Comment by BRousserie** [comment]
Ok, thank you for your advice !
I'll try to learn how to do this shader with URP.
If I find the way to make it, do you want me to create a pull request for the "URP-version" of the shader ? Maybe it could help other users of your package who also want to use the URP, so I'll be happy to share.

**Comment by silverua** [comment]
Yeah, if you'd be willing to share, we can definitely include it. But probably just the shader because I have no intention fully switching the project to URP for everyone who downloads it. Having an option that works in URP would be nice 4 sure.
