### ISSUE TITLE
The layer setting didn't show up as the one in video

### ISSUE THREAD

**Issue by tanliyoung** [silverua/slay-the-spire-map-in-unity#7]
Hi mate, thanks for making this map generator. I really like it. When to import it to my project, I couldn't see the setting for the layers. I am using the **Unity 2019.3.0f6** version. Not sure if that's the cause.
![image](https://user-images.githubusercontent.com/45649672/86240717-0b513e00-bbe5-11ea-89fd-7547aeadda0c.png)

**Comment by tanliyoung** [comment]
I tried it on a new clean project. It works fine. So it can be closed. :)

**Comment by silverua** [comment]
Hi. 
I have used this exact same version of Unity to develop the project and the map is shown correctly on my end (Unity 2019.3.0f6). 
If you just pull the project from Github and open it (without importing into your project), are the Layers shown properly?
Do you have any errors in the console in your project when this happens?
The warning that you're getting basically means that it does not recognize the type as ReorderableArray or that it does not inherit from ReorderableArray.
Are you sure that you have not changed any of the code in MapConfig.cs? Does it still look like this?
```
        [Reorderable]
        public ListOfMapLayers layers;

        [System.Serializable]
        public class ListOfMapLayers : ReorderableArray<MapLayer>
        {
        }
```
