### ISSUE TITLE
OneLine Namespace

### ISSUE THREAD

**Issue by mileswolf7** [silverua/slay-the-spire-map-in-unity#8]
I've imported the entire project package but I seem to be countering an issue with a missing Namespace

using OneLine;

More specifically  it's causing issues with these lines of code:

   [OneLineWithHeader]
        public IntMinMax numOfPreBossNodes;
        [OneLineWithHeader]
        public IntMinMax numOfStartingNodes;

Am I missing a project file?

**Comment by mileswolf7** [comment]
This was fixed by importing the free asset OneLine, but now I'm also encountering the issue: 
Cannot implicitly convert type `System.Type' to `Type'
 [SerializeField, Reorderable(surrogateType = typeof(GameObject), surrogateProperty = "gameObject")]

**Comment by silverua** [comment]
We've added OneLine as a package into Packages/manifest.json
These lines:
    "st.one-line": "https://github.com/slavniyteo/one-line.git#master",
    "st.rect-ex": "https://github.com/slavniyteo/rect-ex.git#master",

You can try adding them into Packages/manifest.json in your project, then let Unity download and import packages. 
Let me know if it fixes the issue.

2nd question - have not encountered this myself, do not have an answer right away. If you get stuck on this for a while, you can send the project over, I'll take a look.

**Comment by mileswolf7** [comment]
Thanks I just tested this all in a fresh project and it works fine. It's probably something to do with how my old project was set up. 

Thanks for the help on this!!
